In [1]:
import pandas as pd

In [2]:
s=pd.Series([100,82,33,77,130,90,45,120,60,21])

In [3]:
s.values

array([100,  82,  33,  77, 130,  90,  45, 120,  60,  21])

In [4]:
s.name="balance"
print(s.name)

balance

In [5]:
# s[0]
s[:4]

0    100
1     82
2     33
3     77
Name: balance, dtype: int64

In [6]:
s.iloc[2]

np.int64(33)

In [7]:
s.iloc[[2,4]]

2     33
4    130
Name: balance, dtype: int64

In [8]:
guys=["john","maria","david","jard","michael","susan","bob","alice","tom","jerry"]
guys

['john',
 'maria',
 'david',
 'jard',
 'michael',
 'susan',
 'bob',
 'alice',
 'tom',
 'jerry']

In [9]:
s.index=guys
s

john       100
maria       82
david       33
jard        77
michael    130
susan       90
bob         45
alice      120
tom         60
jerry       21
Name: balance, dtype: int64

In [10]:
print(s['david'])
print(s.loc['jard'])

33
77

In [11]:
s["maria":"john"]

Series([], Name: balance, dtype: int64)

In [12]:
s[["jard","maria"]]

jard     77
maria    82
Name: balance, dtype: int64

### operations

In [13]:
s>90

john        True
maria      False
david      False
jard       False
michael     True
susan      False
bob        False
alice       True
tom        False
jerry      False
Name: balance, dtype: bool

In [14]:
s[s>50]

john       100
maria       82
jard        77
michael    130
susan       90
alice      120
tom         60
Name: balance, dtype: int64

In [15]:
(s>50) & (s<100)

john       False
maria       True
david      False
jard        True
michael    False
susan       True
bob        False
alice      False
tom         True
jerry      False
Name: balance, dtype: bool

In [16]:
s[(s>50) & (s<100)]

maria    82
jard     77
susan    90
tom      60
Name: balance, dtype: int64

In [17]:
s["bob"]

np.int64(45)

In [18]:
# modifying values
s["bob"]=170
s["bob"]

np.int64(170)

# DATAFRAMES

In [19]:
import numpy as np
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [20]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [21]:
df=pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [22]:
df.head(3)

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [23]:
df.tail(2)

    Name   Age Department   Salary
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [24]:
df.iloc[2]

Name          Charlie
Age              35.0
Department    Finance
Salary        70000.0
Name: 2, dtype: object

In [25]:
df.iloc[1:4]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0

In [26]:
df.loc[1:4, ["Department", "Salary"]]

  Department   Salary
1         IT  60000.0
2    Finance  70000.0
3         IT  62000.0
4         HR      NaN

In [27]:
df.iloc[1:4, :2]

      Name   Age
1      Bob  30.0
2  Charlie  35.0
3    David   NaN

In [28]:
df["Age"]

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [29]:
df[["Name", "Salary"]]

      Name   Salary
0    Alice  50000.0
1      Bob  60000.0
2  Charlie  70000.0
3    David  62000.0
4      Eve      NaN
5    Alice  50000.0

In [30]:
df.drop("Age", axis=1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [31]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [32]:
df.drop("Age", axis=1, inplace=True)

In [33]:
df

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [34]:
df.shape

(6, 3)

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Department  6 non-null      str
 2   Salary      5 non-null      float64
dtypes: float64(1), str(2)
memory usage: 276.0 bytes

In [36]:
s=pd.Series(df.loc[1:4, "Salary"])
s

1    60000.0
2    70000.0
3    62000.0
4        NaN
Name: Salary, dtype: float64

In [37]:
df.describe()

             Salary
count      5.000000
mean   58400.000000
std     8532.291603
min    50000.000000
25%    50000.000000
50%    60000.000000
75%    62000.000000
max    70000.000000

In [38]:
df.iloc[0:, 2]+5000

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [39]:
df.iloc[:,2]

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4        NaN
5    50000.0
Name: Salary, dtype: float64

In [40]:
df.iloc[:,2]=df.iloc[:,2]+5000
df

      Name Department   Salary
0    Alice         HR  55000.0
1      Bob         IT  65000.0
2  Charlie    Finance  75000.0
3    David         IT  67000.0
4      Eve         HR      NaN
5    Alice         HR  55000.0

In [41]:
df["Increment"]=df["Salary"]*0.3-1200
df

      Name Department   Salary  Increment
0    Alice         HR  55000.0    15300.0
1      Bob         IT  65000.0    18300.0
2  Charlie    Finance  75000.0    21300.0
3    David         IT  67000.0    18900.0
4      Eve         HR      NaN        NaN
5    Alice         HR  55000.0    15300.0

In [42]:
df["New Salary"]=df["Salary"]+df["Increment"]
df

      Name Department   Salary  Increment  New Salary
0    Alice         HR  55000.0    15300.0     70300.0
1      Bob         IT  65000.0    18300.0     83300.0
2  Charlie    Finance  75000.0    21300.0     96300.0
3    David         IT  67000.0    18900.0     85900.0
4      Eve         HR      NaN        NaN         NaN
5    Alice         HR  55000.0    15300.0     70300.0

# Data Cleaning

In [53]:
df["Age"]=[25, 30, 35, np.nan, 29, 25]
df

      Name Department   Salary  Increment  New Salary   Age
0    Alice         HR  55000.0    15300.0     70300.0  25.0
1      Bob         IT  65000.0    18300.0     83300.0  30.0
2  Charlie    Finance  75000.0    21300.0     96300.0  35.0
3    David         IT  67000.0    18900.0     85900.0   NaN
4      Eve         HR      NaN        NaN         NaN  29.0
5    Alice         HR  55000.0    15300.0     70300.0  25.0

In [54]:
df.isnull().sum()

Name          0
Department    0
Salary        1
Increment     1
New Salary    1
Age           1
dtype: int64

In [55]:
df.dropna(how="any")

      Name Department   Salary  Increment  New Salary   Age
0    Alice         HR  55000.0    15300.0     70300.0  25.0
1      Bob         IT  65000.0    18300.0     83300.0  30.0
2  Charlie    Finance  75000.0    21300.0     96300.0  35.0
5    Alice         HR  55000.0    15300.0     70300.0  25.0

In [56]:
df.dropna(how="all") #if all the values in a row are null

      Name Department   Salary  Increment  New Salary   Age
0    Alice         HR  55000.0    15300.0     70300.0  25.0
1      Bob         IT  65000.0    18300.0     83300.0  30.0
2  Charlie    Finance  75000.0    21300.0     96300.0  35.0
3    David         IT  67000.0    18900.0     85900.0   NaN
4      Eve         HR      NaN        NaN         NaN  29.0
5    Alice         HR  55000.0    15300.0     70300.0  25.0

In [57]:
df.fillna(0)

      Name Department   Salary  Increment  New Salary   Age
0    Alice         HR  55000.0    15300.0     70300.0  25.0
1      Bob         IT  65000.0    18300.0     83300.0  30.0
2  Charlie    Finance  75000.0    21300.0     96300.0  35.0
3    David         IT  67000.0    18900.0     85900.0   0.0
4      Eve         HR      0.0        0.0         0.0  29.0
5    Alice         HR  55000.0    15300.0     70300.0  25.0

In [60]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [61]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [ ]:
df.fillna(method="ffill")

      Name Department   Salary  Increment  New Salary   Age
0    Alice         HR  55000.0    15300.0     70300.0  25.0
1      Bob         IT  65000.0    18300.0     83300.0  30.0
2  Charlie    Finance  75000.0    21300.0     96300.0  35.0
3    David         IT  67000.0    18900.0     85900.0   NaN
4      Eve         HR      NaN        NaN         NaN  29.0
5    Alice         HR  55000.0    15300.0     70300.0  25.0

In [66]:
df_dup=df[df.duplicated(keep="last")]
df_dup

    Name Department   Salary  Increment  New Salary   Age
0  Alice         HR  55000.0    15300.0     70300.0  25.0

In [69]:
df=df.drop_duplicates()
df

      Name Department   Salary  Increment  New Salary   Age
0    Alice         HR  55000.0    15300.0     70300.0  25.0
1      Bob         IT  65000.0    18300.0     83300.0  30.0
2  Charlie    Finance  75000.0    21300.0     96300.0  35.0
3    David         IT  67000.0    18900.0     85900.0   NaN
4      Eve         HR      NaN        NaN         NaN  29.0

# LAMBDA

In [85]:
data2 = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}
df2=pd.DataFrame(data2)
df2

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [86]:
df2.isnull().sum()

Name          0
Age           1
Department    0
Salary        1
dtype: int64

In [87]:
df2

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [91]:
df2=df2.fillna(61000)
df2

      Name      Age Department   Salary
0    Alice     25.0         HR  50000.0
1      Bob     30.0         IT  60000.0
2  Charlie     35.0    Finance  70000.0
3    David  61000.0         IT  62000.0
4      Eve     29.0         HR  61000.0
5    Alice     25.0         HR  50000.0

In [ ]:
df2["Salary"].mean()

np.float64(58833.333333333336)